/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejercicio_cuatro_casas;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author Mark Gonzalez
 */
public class VistaCasas extends javax.swing.JFrame {

    private List<Casa> listaCasas;
    private DefaultTableModel modeloTabla;

    /**
     * Creates new form VistaCasas
     */
    public VistaCasas() {
        initComponents();
        listaCasas = new ArrayList<>();
        modeloTabla = (DefaultTableModel) tablaCasas.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAnchoCasa = new javax.swing.JTextField();
        txtAltoCasa = new javax.swing.JTextField();
        txtNumPisosCasa = new javax.swing.JTextField();
        btnGuardarCasa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCasas = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtCasasHomonimas = new javax.swing.JTextField();
        btnBuscasCasasHomonimas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("CASAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Ancho de la casa:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Alto de la casa:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Num de pisos:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        jPanel1.add(txtAnchoCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 300, -1));
        jPanel1.add(txtAltoCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 300, -1));
        jPanel1.add(txtNumPisosCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 300, -1));

        btnGuardarCasa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardarCasa.setText("Guardar casa");
        btnGuardarCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCasaActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        tablaCasas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ancho", "Alto", "Num Pisos"
            }
        ));
        jScrollPane1.setViewportView(tablaCasas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 430, 200));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("TOTAL CASAS HOMÓNIMAS:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));
        jPanel1.add(txtCasasHomonimas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 200, -1));

        btnBuscasCasasHomonimas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscasCasasHomonimas.setText("Buscar casas homónimas");
        btnBuscasCasasHomonimas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscasCasasHomonimasActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscasCasasHomonimas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarCasa() {
        try {
            double ancho = Double.parseDouble(txtAnchoCasa.getText().trim());
            double alto = Double.parseDouble(txtAltoCasa.getText().trim());
            int numPisos = Integer.parseInt(txtNumPisosCasa.getText().trim());

            if (ancho <= 0 || alto <= 0 || numPisos <= 0) {
                throw new NumberFormatException("Los valores deben ser mayores a 0.");
            }

            Casa casa = new Casa(ancho, alto, numPisos);
            listaCasas.add(casa);
            modeloTabla.addRow(new Object[]{ancho, alto, numPisos});
            txtAnchoCasa.setText("");
            txtAltoCasa.setText("");
            txtNumPisosCasa.setText("");

            guardarEnArchivo(); // Guardar datos en el archivo después de guardar la casa

            javax.swing.JOptionPane.showMessageDialog(this, "Casa guardada correctamente.");
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error: Ingrese valores numéricos válidos mayores a 0.",
                    "Error de entrada",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void buscarCasasHomonimas() {
        List<Casa> homonimas = Casa.encontrarCasasHomonimas(listaCasas);
        txtCasasHomonimas.setText(String.valueOf(homonimas.size()));

        // Mostrar detalles de las casas homónimas en un JOptionPane
        if (!homonimas.isEmpty()) {
            StringBuilder mensaje = new StringBuilder("Casas homónimas encontradas:\n");
            for (Casa casa : homonimas) {
                mensaje.append(String.format("Ancho: %.2f, Alto: %.2f, Pisos: %d\n",
                        casa.getAncho(), casa.getAlto(), casa.getNumPisos()));
            }
            javax.swing.JOptionPane.showMessageDialog(this, mensaje.toString());
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontraron casas homónimas.");
        }
    }

    private void guardarEnArchivo() {
        String archivo = "casas.txt";
        try (BufferedWriter escritor = new BufferedWriter(new FileWriter(archivo))) {
            // Escribir las casas en el archivo
            escritor.write("Lista de casas:\n");
            for (Casa casa : listaCasas) {
                escritor.write(String.format("Ancho: %.2f, Alto: %.2f, Pisos: %d\n",
                        casa.getAncho(), casa.getAlto(), casa.getNumPisos()));
            }

            // Buscar casas homónimas y escribir el total
            List<Casa> homonimas = Casa.encontrarCasasHomonimas(listaCasas);
            escritor.write("\nTotal de casas homónimas: " + homonimas.size() + "\n");

            if (!homonimas.isEmpty()) {
                escritor.write("Casas homónimas encontradas:\n");
                for (Casa casa : homonimas) {
                    escritor.write(String.format("Ancho: %.2f, Alto: %.2f, Pisos: %d\n",
                            casa.getAncho(), casa.getAlto(), casa.getNumPisos()));
                }
            }

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Datos guardados en el archivo: " + archivo);
        } catch (IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al guardar en el archivo: " + e.getMessage(),
                    "Error de escritura",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }


    private void btnGuardarCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCasaActionPerformed
        guardarCasa();
    }//GEN-LAST:event_btnGuardarCasaActionPerformed

    private void btnBuscasCasasHomonimasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscasCasasHomonimasActionPerformed
        buscarCasasHomonimas();
    }//GEN-LAST:event_btnBuscasCasasHomonimasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCasas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCasas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCasas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCasas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCasas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscasCasasHomonimas;
    private javax.swing.JButton btnGuardarCasa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCasas;
    private javax.swing.JTextField txtAltoCasa;
    private javax.swing.JTextField txtAnchoCasa;
    private javax.swing.JTextField txtCasasHomonimas;
    private javax.swing.JTextField txtNumPisosCasa;
    // End of variables declaration//GEN-END:variables
}
